services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    # entrypoint i CMD już w obrazie

  soap:
    build:
      context: ./soap_service
    env_file:
      - ./backend/.env   # korzysta z DB_CONFIG z tego samego .env
    depends_on:
      - db
    ports:
      - "8002:8002"

volumes:
  pgdata: