"""Increase password_hash field size

Revision ID: 03aa2ba61cd0
Revises: b3f37913a5e2
Create Date: 2025-06-13 15:54:56.218531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03aa2ba61cd0'
down_revision = 'b3f37913a5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
