"""initial structure

Revision ID: e83e53606e0c
Revises: 8c1e7ea6ab40
Create Date: 2025-06-13 15:28:23.514389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83e53606e0c'
down_revision = '8c1e7ea6ab40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('indicator_pkey'))
    )
    # ### end Alembic commands ###
